### PR TITLE
refactor: Extract exif journey into separate wizard

### PR DESCRIPTION
**Pull request by merlinc**
## Proposed changes

Extract `exif` into separate `form-wizard`

### What changed

- Refactored files to use a separate form-wizard for the exif journey.
- Added `debug` to app startup options
- 

### Why did it change

Separating out the "sub-forms" in this way will allow for simpler implementations of the Onfido and Idemia journeys.

Note: This PR breaks the upload functionality for exif for some reason.
As EXIF is a toy implementation, this can be fixed up in a later PR if required

### Issue tracking

- [PYI-179](https://govukverify.atlassian.net/browse/PYI-179)

### Environment variables or secrets

- [x] No environment variables or secrets were added or changed

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

### CODE REVIEW

**Comment by martin-bucinskas** [comment]
Should the files in `views/` directory not be `.njk` instead of `.html`?

**Review by martin-bucinskas — APPROVED** [review]
Looks good, would love to have some useful error logging out to STDOUT too though

**Comment by merlinc** [comment]
> Should the files in `views/` directory not be `.njk` instead of `.html`?

Yeah, that would be cool - cos then the syntax highlighting would work!

There's somewhere in the `hmpo-app` / `hmpo-components` that currently requires it as `html` - another framework bug to be fied.

**Comment by merlinc** [comment]
> Looks good, would love to have some useful error logging out to STDOUT too though

So there's an interesting difference between oldschool `Express` apps and Java style logging - [debug('moduleName')](https://github.com/visionmedia/debug). This throws in logging messages that are ignored unless there is an environment variable set.

Currently my startup config looks like this:

```
      - key: "DEBUG"
        value: "selfie*,busboy-body-parser*,-express*,hmpo-app*"
```

which is allowing me to introspect `selfie`, the `upload` and `hmpo-app` - and turn on super noisy `express` where I need to.

This ability should definitely be added into the documentation.

But I'm not entirely sure how to match it up with `DEBUG_LEVEL=info`

**Comment by merlinc** [comment]
I'm going to create an issue for use better error logging, and merge this PR, as there are others backing up behind it

**Pull request merged**
